package com.amtech.vendorservices.V.Order.Model.MAllOrder

data class Servrequest(
    val accept_by: String,
    val child: Any,
    val country: String,
    val created_at: String,
    val customer_id: String,
    val description: String,
    val details: Any,
    val document: String,
    val driv_type: Any,
    val end_time: String,
    val food_type: String,
    val id: Int,
    val name: String,
    val order_id: String,
    val pay_remain: Any,
    val pay_type: Any,
    val price: String,
    val res_id: String,
    val serv_date: String,
    val serv_hour: String,
    val serv_id: String,
    val start_time: String,
    val status: Int,
    val tr_from: String,
    val tr_to: String,
    val trperson: Any,
    val type: String,
    val updated_at: String,
    val ven_id: String,
    val whchserv: String
)